name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:stable

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y clang gcc libunwind-dev libclang-dev llvm-dev strace wget curl \
            autoconf automake libtool make pkg-config build-essential git

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy, rustfmt

      - name: Build
        run: cargo build --verbose

      - name: Run Rustfmt
        run: cargo fmt -- --check

      - name: Run Clippy
        run: cargo clippy

      - name: Run Tests
        run: RUST_BACKTRACE=1 cargo test --verbose